### ISSUE TITLE
Feature Requeset:

### ISSUE THREAD

**Issue by franckflo** [Octarines/FoundryHourglass#1]
Hi Octarines, thanks a lot for that lovely module, I have many uses for them. I'd like to suggest a few feature requests if you have time:

- Being able to create presets that could be called quickly rather than configuring them every time. 
OR
- Being able to export an hourglass and its configuration as a macro that could be called quickly

- Being able to configure a sound loop that could play while an hourglass is running and a final sound to play once the hourglass expires.

Thanks again!

**Comment by franckflo** [comment]
Awesome!

**Comment by Octarines** [comment]
I have captured the remaining suggestions for the inclusion of sound based elements on my backlog so will close this issue. thanks again
