### ISSUE TITLE
[Request] Timer reset

### ISSUE THREAD

**Issue by schnoodly** [Octarines/FoundryHourglass#12]
Some puzzles I have planned involve a timer that can be reset by certain actions. In addition to pausing and resuming, it would be convenient if I could press a button to restart/reset the hourglass, instead of needing to end that one and start another.

**Comment by Octarines** [comment]
Apologies for the slow reply. This is actually a feature I already have on my list and I am intending it be the next thing I work on. I'm afraid I am in the midst of a house move though so it may be a little while.

**Comment by kiloforce** [comment]
+1 yes please

**Comment by Octarines** [comment]
Added this functionality in v1.7.0 (https://github.com/Octarines/FoundryHourglass/releases/tag/v1.7.0).
Thanks for the feedback and hope you enjoy the changes!
