### ISSUE TITLE
[Request] GM options to cancel and auto close timer

### ISSUE THREAD

**Issue by kiloforce** [Octarines/FoundryHourglass#13]
1. The GM can pause the timer, but there doesn't seem to be a way for the GM to cancel/close the timer for the players.  This can needlessly clutter of the players screen.
2. Would also be nice if there were a checkbox option added to "auto" close the timer window after the timer runs out (and any sound is played).

**Comment by kiloforce** [comment]
I would like to append #1.  I couldn't think of a situation where a hourglass timer should continue if the DM closes it.  So the "cancel" request should simply be: if the DM closes the hourglass window, it should auto close on all player's screens too.

**Comment by Octarines** [comment]
hey @kiloforce, I have tried to add something to this nature in the past but it seems as if there were some quirks about calling "close" commands within an "app" closing the whole program down so I parked it. Now I know there is a desire for this I will do some homework again on it.

**Comment by kiloforce** [comment]
Just wanted to come back and thank you.  This has worked great!
