### ISSUE TITLE
v9

### ISSUE THREAD

**Issue by brunocalado** [Octarines/FoundryHourglass#3]
Hi.

Please remove the foundry vtt warning.

Replace "compatibleCoreVersion":"0.9.0" by "compatibleCoreVersion":"9"

**Comment by Octarines** [comment]
Good morning @brunocalado, apologies this took so long to release but v1.2.0 of Hourglass is now released and is compatible with FoundryVTT core version 9. Thanks for logging this and I shall keep a much closer eye on open issues in future!

**Comment by brunocalado** [comment]
thank you very much
