### ISSUE TITLE
Request: Display a Smaller icon instead of the giant window so that it can stay open on the screen

### ISSUE THREAD

**Issue by jocolamarco** [Octarines/FoundryHourglass#4]

**Comment by Octarines** [comment]
hey @jocolamarco, I was planning at some point to add a resizable version of the window but from what you have described would a size selection option be more what you were thinking (Options screen dropdown Small, Medium, Large) ?

**Comment by jocolamarco** [comment]
That would definitely work for my use case.
A window the same width as the player list would be ideal

**Comment by lucaspicerni** [comment]
I thought the same. I use very long timers (20 or even 30 minutes) so it takes up a lot of screen space. A size option would be great! Tics in the last seconds too, to intensify tense situations.
