### ISSUE TITLE
pause the timer

### ISSUE THREAD

**Issue by BrotherSharper** [Octarines/FoundryHourglass#5]
sometimes a player might need to pause due to IRL reasons, it would be great to have a pause button for the timer.

**Comment by Octarines** [comment]
That's a great idea, especially for longer timed events.

**Comment by KaiderWeise** [comment]
I would love that featue!

**Comment by Octarines** [comment]
Release 1.4.0 (hot fixed to 1.4.1) contains the requested Pause function. Thanks for the great suggestion! Have added you as contributor @BrotherSharper
