### ISSUE TITLE
Play sound when Hourglass finishes

### ISSUE THREAD

**Issue by oamsden** [Octarines/FoundryHourglass#6]
This is a feature request, not an issue.
Having the ability to play a sound when the hourglass finishes would be very helpful.  Additionally if that sound is assignable, it would be even better.

**Comment by Octarines** [comment]
Great suggestion, thanks. I'll let you know when I have a build out with this in.

**Comment by Octarines** [comment]
Release 1.4.0 (hot fixed to 1.4.1) contains the suggestion of assignable (and uploadable) "End Sounds". Thanks for the great idea. I have added you as contributor on the release @oamsden.
